name: Live Stream to Facebook

on:
  workflow_dispatch:
    inputs:
      stream_key:
        description: 'Facebook Stream Key'
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Start Live Stream to Facebook
      run: |
        echo "Starting stream to Facebook..."
        
        # روابط M3U8 الخاصة بالقنوات
        m3u8_urls=(
          "https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
          "https://live4.beinconnect.us/YallaGoalApp/beINSports2.m3u8"
          "https://live4.beinconnect.us/YallaGoalApp/beINSports3.m3u8"
        )

        # Facebook Stream Key
        stream_key="FB-122163568736260989-0-AbyRANJp5RcNj9g_"

        # تشغيل البث باستخدام FFmpeg لكل رابط M3U8
        for url in "${m3u8_urls[@]}"; do
          echo "Starting stream for $url"
          ffmpeg -i "$url" \
            -c:v libx264 -c:a aac -preset fast -tune zerolatency \
            -b:v 1500k -maxrate 1500k -bufsize 3000k \
            -f flv "rtmps://live-api-s.facebook.com:443/rtmp/${stream_key}"
        done
