name: Stream M3U8 to Facebook

on:
  push:
    branches:
      - main  # سيتم تفعيل هذا الـ Action عندما يتم الدفع للفرع 'main'

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Start streaming to Facebook
      run: |
        # روابط M3U8 الخاصة بالقنوات
        m3u8_url_1="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
        m3u8_url_2="https://live4.beinconnect.us/YallaGoalApp/beINSports2.m3u8"
        m3u8_url_3="https://live4.beinconnect.us/YallaGoalApp/beINSports3.m3u8"

        # Stream Key من فيسبوك
        stream_key="FB-122163568736260989-0-AbyRANJp5RcNj9g_"

        # إعداد FFmpeg للبث إلى فيسبوك
        ffmpeg -i "$m3u8_url_1" -c:v libx264 -c:a aac -preset fast -tune zerolatency -b:v 1500k -f flv \
               -i "$m3u8_url_2" -c:v libx264 -c:a aac -preset fast -tune zerolatency -b:v 1500k -f flv \
               -i "$m3u8_url_3" -c:v libx264 -c:a aac -preset fast -tune zerolatency -b:v 1500k -f flv \
               -filter_complex "[0:v][0:a][1:v][1:a][2:v][2:a]concat=n=3:v=1:a=1[v][a]" \
               -map "[v]" -map "[a]" \
               -f flv "rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"
