name: Live Stream to Facebook

on:
  schedule:
    - cron: '*/5 * * * *' # تشغيل البث كل 5 دقائق
  workflow_dispatch: # لبدء البث يدويًا من واجهة GitHub

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Start live streaming
        env:
          M3U8_URL: "https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8" # رابط M3U8 الخاص بك
          RTMP_URL: "rtmps://live-api-s.facebook.com:443/rtmp/FB-122163551444260989-0-AbzI8UAZAv2B1MoW" # مفتاح البث الجديد
        run: |
          ffmpeg -re -i $M3U8_URL -vf "drawtext=text='imad tv.com':fontcolor=white:fontsize=20:alpha=0.5:x=W-w-10:y=H-h-10" \
          -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -c:a aac -b:a 128k -ar 44100 -f flv \
          -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
          $RTMP_URL
